server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ragdb?currentSchema=payment
    username: raguser
    password: ragpass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: payment